Feature player
Kukushenok/Evercold pull request #10
Opened 2024-10-27 16:36 UTC by AinzZamma

Open New Version 1.0.0

2024-10-27 17:44 UTC, Kukushenok commented on Assets/Features/Player/Scripts/BasePlayerLocomotion.cs
> +        byte[] utf8 = Encoding.UTF8.GetBytes("���������");
.... зачем.


![image](https://github.com/user-attachments/assets/682a051e-3ed0-41b6-bffc-dec2e8c941f7)

2024-10-27 17:45 UTC, Kukushenok commented on Assets/Features/Player/Scripts/CameraLocomotionFeature.cs
> +    //�������� ������
исправь комментарии T-T

2024-10-27 17:47 UTC, Kukushenok commented on Assets/Features/Player/Scripts/CharacterControllerLocomotion.cs
> +        private Vector3 cameraRotation;
_cameraRotation поправильней будет

2024-10-27 17:49 UTC, Kukushenok commented on Assets/Features/Player/Scripts/CharacterControllerLocomotion.cs
> +                playerCamera = Camera.main;
Так, вот это лучше правда не делать, поскольку если внезапно в сцене появится другая камера, я разочаруюсь в том, что игрок использует другую как главную

сделай private Transform _camera
тогда никто не мешает сделать, чтобы камера уже имела определённый localPosition и localRotation в самом редакторе, а не скрипте.

2024-10-27 17:50 UTC, Kukushenok commented on Assets/Features/Player/Scripts/CharacterControllerLocomotion.cs
> +
было бы хорошо, если бы код разделяла максимум 1 пустая строка

2024-10-27 17:52 UTC, Kukushenok requested changes
Чуть чуть осталось исправлений и можно будет сливать.

2024-10-27 17:57 UTC, Kukushenok commented on Assets/Features/Player/Scripts/CharacterControllerLocomotion.cs
> +                playerCamera = Camera.main;
убери из BasePlayerLocomotion поле playerCamera

2024-10-27 18:24 UTC, AinzZamma commented on Assets/Features/Player/Scripts/BasePlayerLocomotion.cs
> +        byte[] utf8 = Encoding.UTF8.GetBytes("���������");
Это тот самый один из способов конвертирования

2024-11-09 16:58 UTC, Kukushenok approved these changes
Рефакторинг

2024-11-09 17:00 UTC, merged